version: 0.1
os: linux
files:
 - Sources: /
   destination: home/ec2-user/Ghost
hooks:
 ApplicationStop:
  - location: Scripts/application_stop.sh
    timeout: 300
    runas: ec2-user
Beforeinstall:
 - location: Scripts/before_install.sh
   timeout: 300
   runas: ec2-user
AplicationStart:
 - location: Scripts/application_start.sh
   timeout: 300
   runas: ec2-user
