version: 0.0
os: linux 
files:
   - source: /
     destination: /home/ec2-user/Ghost
hooks:
  BeforeInstall:
    - location: Scripts/before_install.sh
      timeout: 300
      runas: ec2-user  
  ApplicationStart:
    - location: Scripts/application_start.sh
      timeout: 300
      runas: ec2-user
  ApplicationStop:
    - location: Scripts/application_stop.sh
      timeout: 300
      runas: ec2-user
