version: 0.2

phases:
  install:
    runtime-versions: nodejs: 10
      java: corretto8
  build:
    commands:
      - echo Build started on `date`
      - mvn test 
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
artifacts:
  files:
    - target/Ghost
    - appspec.yml
  discard-paths: yes
